blank_issues_enabled: false
contact_links:
  - name: DocScribe Ruby Gem Issues
    url: https://github.com/unurgunite/docscribe/issues
    about: Report bugs or suggest features for the DocScribe Ruby gem itself.
